export const tarotDeck = [
  {
    id: "0",
    name: "The Fool",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/0.png",
    keywords: ["beginnings", "innocence", "freedom"],
    reversedKeywords: ["recklessness", "naivety", "folly"],
  },
  {
    id: "1",
    name: "The Magician",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/1.png",
    keywords: ["manifestation", "resourcefulness", "power"],
    reversedKeywords: ["manipulation", "poor planning", "untapped potential"],
  },
  {
    id: "2",
    name: "The High Priestess",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/2.png",
    keywords: ["intuition", "divine feminine", "mystery"],
    reversedKeywords: ["secrets", "disconnection", "withdrawal"],
  },
  {
    id: "3",
    name: "The Empress",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/3.png",
    keywords: ["abundance", "fertility", "nurturing"],
    reversedKeywords: ["dependence", "creative block", "smothering"],
  },
  {
    id: "4",
    name: "The Emperor",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/4.png",
    keywords: ["authority", "structure", "stability"],
    reversedKeywords: ["control", "rigidity", "domination"],
  },
  {
    id: "5",
    name: "The Hierophant",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/5.png",
    keywords: ["tradition", "spirituality", "guidance"],
    reversedKeywords: ["rebellion", "unorthodoxy", "freedom"],
  },
  {
    id: "6",
    name: "The Lovers",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/6.png",
    keywords: ["love", "harmony", "choices"],
    reversedKeywords: ["conflict", "imbalance", "disharmony"],
  },
  {
    id: "7",
    name: "The Chariot",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/7.png",
    keywords: ["willpower", "victory", "determination"],
    reversedKeywords: ["lack of direction", "aggression", "self-doubt"],
  },
  {
    id: "8",
    name: "Strength",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/8.png",
    keywords: ["courage", "inner strength", "compassion"],
    reversedKeywords: ["weakness", "insecurity", "self-doubt"],
  },
  {
    id: "9",
    name: "The Hermit",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/9.png",
    keywords: ["introspection", "wisdom", "solitude"],
    reversedKeywords: ["loneliness", "isolation", "withdrawal"],
  },
  {
    id: "10",
    name: "Wheel of Fortune",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/10.png",
    keywords: ["change", "destiny", "cycles"],
    reversedKeywords: ["bad luck", "resistance to change", "unwelcome surprises"],
  },
  {
    id: "11",
    name: "Justice",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/11.png",
    keywords: ["fairness", "truth", "law"],
    reversedKeywords: ["injustice", "dishonesty", "corruption"],
  },
  {
    id: "12",
    name: "The Hanged Man",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/12.png",
    keywords: ["sacrifice", "letting go", "new perspective"],
    reversedKeywords: ["stalling", "indecision", "resistance"],
  },
  {
    id: "13",
    name: "Death",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/13.png",
    keywords: ["transformation", "endings", "rebirth"],
    reversedKeywords: ["resistance", "fear of change", "stagnation"],
  },
  {
    id: "14",
    name: "Temperance",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/14.png",
    keywords: ["balance", "moderation", "patience"],
    reversedKeywords: ["imbalance", "excess", "lack of vision"],
  },
  {
    id: "15",
    name: "The Devil",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/15.png",
    keywords: ["addiction", "materialism", "temptation"],
    reversedKeywords: ["freedom", "release", "detachment"],
  },
  {
    id: "16",
    name: "The Tower",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/16.png",
    keywords: ["sudden change", "chaos", "awakening"],
    reversedKeywords: ["fear of change", "delayed disaster", "avoidance"],
  },
  {
    id: "17",
    name: "The Star",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/17.png",
    keywords: ["hope", "inspiration", "renewal"],
    reversedKeywords: ["despair", "lack of faith", "disconnection"],
  },
  {
    id: "18",
    name: "The Moon",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/18.png",
    keywords: ["illusion", "intuition", "subconscious"],
    reversedKeywords: ["confusion", "fear", "misinterpretation"],
  },
  {
    id: "19",
    name: "The Sun",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/19.png",
    keywords: ["joy", "success", "positivity"],
    reversedKeywords: ["negativity", "pessimism", "ego"],
  },
  {
    id: "20",
    name: "Judgement",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/20.png",
    keywords: ["rebirth", "absolution", "inner calling"],
    reversedKeywords: ["self-doubt", "regret", "avoidance"],
  },
  {
    id: "21",
    name: "The World",
    arcana: "major",
    image: "../../../public/assets/majorArcanes/21.png",
    keywords: ["completion", "wholeness", "achievement"],
    reversedKeywords: ["lack of closure", "delays", "shortcuts"],
  },
  {
    id: "cups_1",
    name: "Ace of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/1.png",
    keywords: ["new relationships", "emotional awakening", "love"],
    reversedKeywords: ["emotional loss", "blocked creativity", "emptiness"],
  },
  {
    id: "cups_2",
    name: "Two of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/2.png",
    keywords: ["partnership", "mutual attraction", "unity"],
    reversedKeywords: ["disharmony", "imbalance", "broken communication"],
  },
  {
    id: "cups_3",
    name: "Three of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/3.png",
    keywords: ["friendship", "celebration", "community"],
    reversedKeywords: ["isolation", "loneliness", "overindulgence"],
  },
  {
    id: "cups_4",
    name: "Four of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/4.png",
    keywords: ["apathy", "meditation", "contemplation"],
    reversedKeywords: ["awareness", "acceptance", "new opportunities"],
  },
  {
    id: "cups_5",
    name: "Five of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/5.png",
    keywords: ["loss", "grief", "regret"],
    reversedKeywords: ["acceptance", "moving on", "finding peace"],
  },
  {
    id: "cups_6",
    name: "Six of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/6.png",
    keywords: ["nostalgia", "childhood memories", "innocence"],
    reversedKeywords: ["stuck in past", "unrealistic expectations", "naivety"],
  },
  {
    id: "cups_7",
    name: "Seven of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/7.png",
    keywords: ["illusion", "choices", "wishful thinking"],
    reversedKeywords: ["clarity", "determination", "making decisions"],
  },
  {
    id: "cups_8",
    name: "Eight of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/8.png",
    keywords: ["abandonment", "walking away", "spiritual quest"],
    reversedKeywords: ["fear of change", "stagnation", "accepting mediocrity"],
  },
  {
    id: "cups_9",
    name: "Nine of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/9.png",
    keywords: ["contentment", "satisfaction", "wish fulfillment"],
    reversedKeywords: ["greed", "materialism", "dissatisfaction"],
  },
  {
    id: "cups_10",
    name: "Ten of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/10.png",
    keywords: ["happiness", "harmony", "family"],
    reversedKeywords: ["broken home", "family conflict", "disconnection"],
  },
  {
    id: "cups_page",
    name: "Page of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/Page.png",
    keywords: ["creativity", "intuition", "emotional messages"],
    reversedKeywords: ["emotional immaturity", "moodiness", "artistic blocks"],
  },
  {
    id: "cups_knight",
    name: "Knight of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/Knight.png",
    keywords: ["romance", "charm", "following heart"],
    reversedKeywords: ["moodiness", "jealousy", "unrealistic expectations"],
  },
  {
    id: "cups_queen",
    name: "Queen of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/Queen.png",
    keywords: ["compassion", "emotional stability", "intuition"],
    reversedKeywords: ["emotional instability", "moodiness", "dependence"],
  },
  {
    id: "cups_king",
    name: "King of Cups",
    arcana: "minor",
    suit: "cups",
    image: "../../../public/assets/minorArcanesCups/King.png",
    keywords: ["emotional control", "compassion", "diplomacy"],
    reversedKeywords: ["emotional manipulation", "moodiness", "volatility"],
  },
  {
    id: "pentacles_1",
    name: "Ace of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/1.png",
    keywords: ["opportunity", "prosperity", "new financial beginnings"],
    reversedKeywords: ["missed opportunity", "lack of planning", "poor investments"],
  },
  {
    id: "pentacles_2",
    name: "Two of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/2.png",
    keywords: ["balance", "flexibility", "time management"],
    reversedKeywords: ["imbalance", "poor time management", "overwhelmed"],
  },
  {
    id: "pentacles_3",
    name: "Three of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/3.png",
    keywords: ["teamwork", "collaboration", "skill building"],
    reversedKeywords: ["lack of teamwork", "poor collaboration", "lack of skill"],
  },
  {
    id: "pentacles_4",
    name: "Four of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/4.png",
    keywords: ["security", "control", "conservatism"],
    reversedKeywords: ["greed", "selfishness", "financial insecurity"],
  },
  {
    id: "pentacles_5",
    name: "Five of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/5.png",
    keywords: ["hardship", "poverty", "isolation"],
    reversedKeywords: ["recovery", "charity", "improvement"],
  },
  {
    id: "pentacles_6",
    name: "Six of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/6.png",
    keywords: ["generosity", "charity", "giving and receiving"],
    reversedKeywords: ["debt", "selfishness", "one-sided charity"],
  },
  {
    id: "pentacles_7",
    name: "Seven of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/7.png",
    keywords: ["patience", "investment", "hard work"],
    reversedKeywords: ["impatience", "lack of reward", "poor investments"],
  },
  {
    id: "pentacles_8",
    name: "Eight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/8.png",
    keywords: ["skill development", "craftsmanship", "hard work"],
    reversedKeywords: ["lack of focus", "perfectionism", "misdirected activity"],
  },
  {
    id: "pentacles_9",
    name: "Nine of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/9.png",
    keywords: ["independence", "luxury", "self-sufficiency"],
    reversedKeywords: ["financial dependence", "setbacks", "lack of discipline"],
  },
  {
    id: "pentacles_10",
    name: "Ten of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/10.png",
    keywords: ["wealth", "inheritance", "family legacy"],
    reversedKeywords: ["financial loss", "family disputes", "lack of stability"],
  },
  {
    id: "pentacles_page",
    name: "Page of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/Page.png",
    keywords: ["manifestation", "financial opportunity", "skill development"],
    reversedKeywords: ["lack of progress", "procrastination", "lack of goals"],
  },
  {
    id: "pentacles_knight",
    name: "Knight of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/Knight.png",
    keywords: ["hard work", "productivity", "routine"],
    reversedKeywords: ["laziness", "obsessiveness", "lack of progress"],
  },
  {
    id: "pentacles_queen",
    name: "Queen of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/Queen.png",
    keywords: ["nurturing", "practical", "resourceful"],
    reversedKeywords: ["self-care neglect", "smothering", "jealousy"],
  },
  {
    id: "pentacles_king",
    name: "King of Pentacles",
    arcana: "minor",
    suit: "pentacles",
    image: "../../../public/assets/minorArcanesPentacles/King.png",
    keywords: ["abundance", "success", "leadership"],
    reversedKeywords: ["greed", "materialism", "financial instability"],
  },
  {
    id: "swords_1",
    name: "Ace of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/1.png",
    keywords: ["clarity", "breakthrough", "new ideas"],
    reversedKeywords: ["confusion", "chaos", "lack of clarity"],
  },
  {
    id: "swords_2",
    name: "Two of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/2.png",
    keywords: ["difficult choice", "indecision", "stalemate"],
    reversedKeywords: ["decision made", "relief", "clarity"],
  },
  {
    id: "swords_3",
    name: "Three of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/3.png",
    keywords: ["heartbreak", "sorrow", "grief"],
    reversedKeywords: ["healing", "forgiveness", "recovery"],
  },
  {
    id: "swords_4",
    name: "Four of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/4.png",
    keywords: ["rest", "meditation", "recovery"],
    reversedKeywords: ["restlessness", "burnout", "lack of progress"],
  },
  {
    id: "swords_5",
    name: "Five of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/5.png",
    keywords: ["conflict", "defeat", "betrayal"],
    reversedKeywords: ["reconciliation", "making amends", "moving on"],
  },
  {
    id: "swords_6",
    name: "Six of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/6.png",
    keywords: ["transition", "moving on", "healing"],
    reversedKeywords: ["stuck in past", "resistance to change", "unfinished business"],
  },
  {
    id: "swords_7",
    name: "Seven of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/7.png",
    keywords: ["deception", "strategy", "getting away"],
    reversedKeywords: ["confession", "honesty", "returning stolen goods"],
  },
  {
    id: "swords_8",
    name: "Eight of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/8.png",
    keywords: ["restriction", "imprisonment", "victimization"],
    reversedKeywords: ["freedom", "release", "self-acceptance"],
  },
  {
    id: "swords_9",
    name: "Nine of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/9.png",
    keywords: ["anxiety", "nightmares", "despair"],
    reversedKeywords: ["hope", "recovery", "learning to cope"],
  },
  {
    id: "swords_10",
    name: "Ten of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/10.png",
    keywords: ["betrayal", "ruin", "rock bottom"],
    reversedKeywords: ["recovery", "regeneration", "lessons learned"],
  },
  {
    id: "swords_page",
    name: "Page of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/Page.png",
    keywords: ["curiosity", "mental energy", "new ideas"],
    reversedKeywords: ["haste", "unfocused energy", "gossip"],
  },
  {
    id: "swords_knight",
    name: "Knight of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/Knight.png",
    keywords: ["action", "impulsiveness", "haste"],
    reversedKeywords: ["recklessness", "impatience", "lack of direction"],
  },
  {
    id: "swords_queen",
    name: "Queen of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/Queen.png",
    keywords: ["independence", "clear thinking", "direct communication"],
    reversedKeywords: ["coldness", "bitterness", "harsh judgment"],
  },
  {
    id: "swords_king",
    name: "King of Swords",
    arcana: "minor",
    suit: "swords",
    image: "../../../public/assets/minorArcanesSwords/King.png",
    keywords: ["authority", "intellectual power", "truth"],
    reversedKeywords: ["manipulation", "abuse of power", "lack of compassion"],
  },
  {
    id: "wands_1",
    name: "Ace of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/1.png",
    keywords: ["inspiration", "new opportunities", "growth"],
    reversedKeywords: ["lack of energy", "delays", "creative blocks"],
  },
  {
    id: "wands_2",
    name: "Two of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/2.png",
    keywords: ["planning", "making decisions", "leaving comfort zone"],
    reversedKeywords: ["fear of unknown", "lack of planning", "bad decisions"],
  },
  {
    id: "wands_3",
    name: "Three of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/3.png",
    keywords: ["expansion", "foresight", "overseas opportunities"],
    reversedKeywords: ["lack of foresight", "delays", "frustration"],
  },
  {
    id: "wands_4",
    name: "Four of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/4.png",
    keywords: ["celebration", "harmony", "homecoming"],
    reversedKeywords: ["lack of support", "instability", "cancelled celebrations"],
  },
  {
    id: "wands_5",
    name: "Five of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/5.png",
    keywords: ["conflict", "competition", "disagreement"],
    reversedKeywords: ["avoiding conflict", "inner conflict", "tension release"],
  },
  {
    id: "wands_6",
    name: "Six of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/6.png",
    keywords: ["victory", "success", "public recognition"],
    reversedKeywords: ["private achievement", "self-doubt", "lack of recognition"],
  },
  {
    id: "wands_7",
    name: "Seven of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/7.png",
    keywords: ["defensiveness", "standing your ground", "protecting position"],
    reversedKeywords: ["giving up", "overwhelmed", "lack of courage"],
  },
  {
    id: "wands_8",
    name: "Eight of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/8.png",
    keywords: ["speed", "rapid action", "movement"],
    reversedKeywords: ["delays", "frustration", "lack of energy"],
  },
  {
    id: "wands_9",
    name: "Nine of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/9.png",
    keywords: ["resilience", "courage", "persistence"],
    reversedKeywords: ["inner resources", "struggle", "overwhelm"],
  },
  {
    id: "wands_10",
    name: "Ten of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/10.png",
    keywords: ["burden", "hard work", "accomplishment"],
    reversedKeywords: ["inability to delegate", "burnout", "collapse"],
  },
  {
    id: "wands_page",
    name: "Page of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/Page.png",
    keywords: ["enthusiasm", "exploration", "excitement"],
    reversedKeywords: ["lack of direction", "procrastination", "lack of experience"],
  },
  {
    id: "wands_knight",
    name: "Knight of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/Knight.png",
    keywords: ["action", "adventure", "impulsiveness"],
    reversedKeywords: ["recklessness", "haste", "lack of self-control"],
  },
  {
    id: "wands_queen",
    name: "Queen of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/Queen.png",
    keywords: ["confidence", "determination", "warmth"],
    reversedKeywords: ["selfishness", "jealousy", "insecurity"],
  },
  {
    id: "wands_king",
    name: "King of Wands",
    arcana: "minor",
    suit: "wands",
    image: "../../../public/assets/minorArcanesWands/King.png",
    keywords: ["leadership", "vision", "honor"],
    reversedKeywords: ["arrogance", "impulsiveness", "ruthlessness"],
  },
];