export const tarotDeck = [
  {
    id: "0",
    name: "The Fool",
    arcana: "major",
    image: "/assets/majorArcanes/0.png",
    keywords: ["beginnings", "innocence", "freedom"],
    reversedKeywords: ["recklessness", "naivety", "folly"],
  },
  {
    id: "1",
    name: "The Magician",
    arcana: "major",
    image: "/assets/majorArcanes/1.png",
    keywords: ["manifestation", "resourcefulness", "power"],
    reversedKeywords: ["manipulation", "poor planning", "untapped potential"],
  },
  {
    id: "2",
    name: "The High Priestess",
    arcana: "major",
    image: "/assets/majorArcanes/2.png",
    keywords: ["intuition", "divine feminine", "mystery"],
    reversedKeywords: ["secrets", "disconnection", "withdrawal"],
  },
  {
    id: "3",
    name: "The Empress",
    arcana: "major",
    image: "/assets/majorArcanes/3.png",
    keywords: ["abundance", "fertility", "nurturing"],
    reversedKeywords: ["dependence", "creative block", "smothering"],
  },
  {
    id: "4",
    name: "The Emperor",
    arcana: "major",
    image: "/assets/majorArcanes/4.png",
    keywords: ["authority", "structure", "stability"],
    reversedKeywords: ["control", "rigidity", "domination"],
  },
  {
    id: "5",
    name: "The Hierophant",
    arcana: "major",
    image: "/assets/majorArcanes/5.png",
    keywords: ["tradition", "spirituality", "guidance"],
    reversedKeywords: ["rebellion", "unorthodoxy", "freedom"],
  },
  {
    id: "6",
    name: "The Lovers",
    arcana: "major",
    image: "/assets/majorArcanes/6.png",
    keywords: ["love", "harmony", "choices"],
    reversedKeywords: ["conflict", "imbalance", "disharmony"],
  },
  {
    id: "7",
    name: "The Chariot",
    arcana: "major",
    image: "/assets/majorArcanes/7.png",
    keywords: ["willpower", "victory", "determination"],
    reversedKeywords: ["lack of direction", "aggression", "self-doubt"],
  },
  {
    id: "8",
    name: "Strength",
    arcana: "major",
    image: "/assets/majorArcanes/8.png",
    keywords: ["courage", "inner strength", "compassion"],
    reversedKeywords: ["weakness", "insecurity", "self-doubt"],
  },
  {
    id: "9",
    name: "The Hermit",
    arcana: "major",
    image: "/assets/majorArcanes/9.png",
    keywords: ["introspection", "wisdom", "solitude"],
    reversedKeywords: ["loneliness", "isolation", "withdrawal"],
  },
  {
    id: "10",
    name: "Wheel of Fortune",
    arcana: "major",
    image: "/assets/majorArcanes/10.png",
    keywords: ["change", "destiny", "cycles"],
    reversedKeywords: ["bad luck", "resistance to change", "unwelcome surprises"],
  },
  {
    id: "11",
    name: "Justice",
    arcana: "major",
    image: "/assets/majorArcanes/11.png",
    keywords: ["fairness", "truth", "law"],
    reversedKeywords: ["injustice", "dishonesty", "corruption"],
  },
  {
    id: "12",
    name: "The Hanged Man",
    arcana: "major",
    image: "/assets/majorArcanes/12.png",
    keywords: ["sacrifice", "letting go", "new perspective"],
    reversedKeywords: ["stalling", "indecision", "resistance"],
  },
  {
    id: "13",
    name: "Death",
    arcana: "major",
    image: "/assets/majorArcanes/13.png",
    keywords: ["transformation", "endings", "rebirth"],
    reversedKeywords: ["resistance", "fear of change", "stagnation"],
  },
  {
    id: "14",
    name: "Temperance",
    arcana: "major",
    image: "/assets/majorArcanes/14.png",
    keywords: ["balance", "moderation", "patience"],
    reversedKeywords: ["imbalance", "excess", "lack of vision"],
  },
  {
    id: "15",
    name: "The Devil",
    arcana: "major",
    image: "/assets/majorArcanes/15.png",
    keywords: ["addiction", "materialism", "temptation"],
    reversedKeywords: ["freedom", "release", "detachment"],
  },
  {
    id: "16",
    name: "The Tower",
    arcana: "major",
    image: "/assets/majorArcanes/16.png",
    keywords: ["sudden change", "chaos", "awakening"],
    reversedKeywords: ["fear of change", "delayed disaster", "avoidance"],
  },
  {
    id: "17",
    name: "The Star",
    arcana: "major",
    image: "/assets/majorArcanes/17.png",
    keywords: ["hope", "inspiration", "renewal"],
    reversedKeywords: ["despair", "lack of faith", "disconnection"],
  },
  {
    id: "18",
    name: "The Moon",
    arcana: "major",
    image: "/assets/majorArcanes/18.png",
    keywords: ["illusion", "intuition", "subconscious"],
    reversedKeywords: ["confusion", "fear", "misinterpretation"],
  },
  {
    id: "19",
    name: "The Sun",
    arcana: "major",
    image: "/assets/majorArcanes/19.png",
    keywords: ["joy", "success", "positivity"],
    reversedKeywords: ["negativity", "pessimism", "ego"],
  },
  {
    id: "20",
    name: "Judgement",
    arcana: "major",
    image: "/assets/majorArcanes/20.png",
    keywords: ["rebirth", "absolution", "inner calling"],
    reversedKeywords: ["self-doubt", "regret", "avoidance"],
  },
  {
    id: "21",
    name: "The World",
    arcana: "major",
    image: "/assets/majorArcanes/21.png",
    keywords: ["completion", "wholeness", "achievement"],
    reversedKeywords: ["lack of closure", "delays", "shortcuts"],
  },
];